### ISSUE TITLE
Stylish does not affect dynamically generated iframes

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/stylish-chrome#3]
From https://github.com/JasonBarnabe/stylish/issues/103

http://forum.userstyles.org/discussion/15032/how-to-apply-css-to-content-within-an-iframe
https://code.google.com/p/chromium/issues/detail?id=76429

**Comment by silverwind** [comment]
@JasonBarnabe anything else that needs to be done here other than adding `match_about_blank` to "permissions"? I could send you a PR, but it's a trivial change :)

**Comment by JasonBarnabe** [comment]
I'm unsure. Why don't you test it out and if that's all that's needed, send a PR.

**Comment by silverwind** [comment]
I'll test it.

**Comment by silverwind** [comment]
It appears it's all that was needed. Here's the iframe after the fix (was white before):

![iframe](https://cloud.githubusercontent.com/assets/115237/5962106/9a438852-a7e1-11e4-84df-eef420e2f1b9.png)

**Comment by Mottie** [comment]
Awesome news! :+1:

**Comment by JasonBarnabe** [comment]
I tested this a bit myself. It makes things better, but still not great.

-Testing on [Tumblr's new post box](https://www.tumblr.com/new/text), it still doesn't work. This is likely because the src is `javascript:""` rather than nothing (`about:blank`).
-Testing on [MDN's editor](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector$edit), it works if you apply the style after the page has loaded, but not if you load the page with the style enabled already. Maybe this is because the iframe's not there when Stylish runs?

**Comment by silverwind** [comment]
For the first case: I think we need to change the [patterns](https://developer.chrome.com/extensions/match_patterns). Will experiment with javascript urls, file:// is also missing there.

For the second case: Maybe something like a mutation observer is needed to re-apply when iframes get added. But there's probably a cleaner solutions out there.

**Comment by JasonBarnabe** [comment]
> For the first case: I think we need to change the patterns. Will experiment with javascript urls, file:// is also missing there.

Chrome's docs say `javascript:` is not allowed. I've added `file:` in #25.

**Comment by silverwind** [comment]
> Chrome's docs say javascript: is not allowed

Can you link me to where you read that? Sounds like another Chromium issue is required.

**Comment by JasonBarnabe** [comment]
[Same doc you linked to.](https://developer.chrome.com/extensions/match_patterns) It lists allowed schemes, and `javascript:` isn't one of them.

A more likely solution is extending `match_about_blank` to `javascript:` URLs, though.

**Comment by silverwind** [comment]
Well, I don't see `javascript:` mentioned explicitly, so I think `<all_urls>` or `*` might be worth a try.

**Comment by silverwind** [comment]
No luck with `<all_urls>` and `*` is not a valid entry. My iframe in question (on `irccloud.com`) doesn't have a `src` attribute, but once I added `github.com` to the matched domains of the style, it did work. Pretty strange nonetheless.

**Comment by silverwind** [comment]
@JasonBarnabe I tried your MDN example, but it works as expected on page reloads. Here's the style I was using:

```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("developer.mozilla.org") {
  .cke_wysiwyg_frame, .cke_wysiwyg_div { margin-left: 50% !important;}
}
```
This is on Chrome  42. Could you verify again that the MDN case works for you?

Also, please point me to the iframe you meant on tumblr. I could only identify a few hidden ones in the HMTL. Maybe `<all_urls>` could solve that case.

**Comment by silverwind** [comment]
Noticed the page reload issue on another site. I think this is only fixable through JS.

**Comment by JasonBarnabe** [comment]
Tumblr must've changed their editor since I tried last, because yeah, there's no iframe involved any more.

**Comment by hideheader** [comment]
(1) Tumblr dropped TinyMCE and began using `contentEditable` elements [on Jan 28](https://forum.userstyles.org/discussion/44908/new-tumblr-update-for-text-editing-help-please-updated-and-urgent-help). The [TinyMCE samples](http://www.tinymce.com/tryit/basic.php) use the same pattern. Chrome doesn't load content scripts into `src='javascript:""'` `iframe`s - the `match_about_blank` fix will always fail on these frames.

(2) The intermittent failure in [MDN's editor](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector%24edit) occurs when Chrome is able to run the content script before the page writes content to the `iframe`. A minimal default document, `<html><head/><body/></html>`, is created in the `iframe` when it's inserted into the DOM. If the page script that writes the `iframe` content runs before the Stylish content script, you see styles. If the content script runs first, Stylish adds styles to the default document, which are subsequently lost when the page replaces the `iframe` content.

The only remedy for intermittent failures like this is to monitor the styles with a MutationObserver and replace them.

(3) Here are some test cases. *Stylish* is *yes* if Chrome ran the content script, *styled* is *yes* if the style was applied, *src* is `<iframe>.src` and *docURI* is `<iframe>.contentDocument.documentURI`.

 | aString | Stylish | styled | src | docURI
--- | ---- | ---- | ---- | ---- | ----
1 | none | yes | yes | http://ace.c9.io/ | http://ace.c9.io/#nav=embedding
2 | '' | yes | yes | http://ace.c9.io/ | http://ace.c9.io/#nav=embedding
3 | `javascript:""` | no | no | javascript:"" | http://ace.c9.io/#nav=embedding
4 | `data:...` | yes | yes | data:... | http://ace.c9.io/#nav=embedding
5 | srcdoc | yes | no | '' | about:srcdoc
6 | none [1] | yes | no | '' | about:blank
7 | `gardez:l.eau` | yes | yes | gardez:l.eau | http://ace.c9.io/#nav=embedding
8 | `#` | yes | yes | http://ace.c9.io/# | http://ace.c9.io/#nav=embedding

[1] `createHTMLDocument()`, then `replaceChild()`
```javascript
// All but cases 5 & 6 set a `src` URL, then write the `contentDocument`
l = document.body.appendChild(document.createElement('iframe'));
l.src = aString; // omitted, if aString is none
d = l.contentDocument; d.open(); d.write(iframeContent); d.close();

// Case 5 sets `srcdoc` to the document content instead of writing `contentDocument`
l = document.body.appendChild(document.createElement('iframe'));
l.srcdoc = iframeContent;

// Case 6 creates a complete `document` de novo, then inserts it into the `iframe`
d=document.implementation.createHTMLDocument('Editor IFRAME')
d.open(); d.write(iframeContent); d.close();

l = document.body.appendChild(document.createElement('iframe'));
d2 = l.contentDocument;
d2.replaceChild(d2.adoptNode(d.documentElement), d2.documentElement);
```
(4) As you can see, 
![Cases 1-6: half fail](https://cloud.githubusercontent.com/assets/10900909/6177498/4e9e5ea0-b2d5-11e4-9312-3479e60ce044.png)
`match_about_blank` really isn't a solution. What's needed is a MutationObserver that copies existing styles from into new frames, another that copies new styles into existing frames, and a third that detects when styles are removed and replaces them when appropriate. The first two are easy. The third requires a little experimentation, since you don't want to reinsert them while the page is being torn down.

**Comment by silverwind** [comment]
Just wanted to say thank you @hideheader, awesome work!

**Comment by hideheader** [comment]
This pull request is a pair of MutationObservers that copy Stylish `STYLE` elements from the top-level document into child `IFRAME`s. I've tested with [the examples above](https://gist.github.com/hideheader/a3b136032503fabc2928) using the [Ace editor](http://ace.c9.io/#nav=embedding), on the [TinyMCE editor](http://www.tinymce.com/tryit/basic.php), and on [MDN's editor](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector%24edit) using [this style](https://userstyles.org/styles/110701/test-anonymous-iframes-tinymce-et-al).  It works with all but `srcdoc='<html/>'` frames, which load `contentDocument` *very* late; those can be handled in `onLoad` on the `IFRAME`. 

The PR only adds styles when the `IFRAME` is added to the DOM, just as `apply.js` does, so there should still be intermittent failures with MDN's editor. Unfortunately it hasn't been failing on MDN, so I need an example page that overwrites frame content after the content script has loaded.

Both `IFRAME.onload` and `webNavigation.onCommitted` fire when frame content is reloaded. Each has issues; test cases are needed to sort them out.

If you want to experiment, the penultimate commit before the PR can add a MutationObserver on `HTML` and `HTML > *`, and an `onLoad` handler on `IFRAMES`. Set `localStorage['observer.observeFrameContent'] = 'true'` and `localStorage['observer.observeFrameLoad'] = 'true'` to enable them.

**Comment by JasonBarnabe** [comment]
Committed a fix to the iframe mutation observer. Evidentally the test page I stole from @hideheader never actually triggered this functionality.

More testing is welcome.

**Comment by hideheader** [comment]
Sure. Blame the test page.

**Comment by hideheader** [comment]
My, that *was* lucky. If you hadn't refactored the code and broken it we still wouldn't know that there's a blind spot in the test cases. What condition is it that wasn't being triggered?

**Comment by JasonBarnabe** [comment]
The iframe mutation observer never ran; I assume because the iframes were added before the content script ran. So everything appeared to work, whether loading the page with the style on or turning it on after load, but only the page load logic was being exercised.

**Comment by JasonBarnabe** [comment]
Fixed the pushState case for feedly.

**Comment by tophf** [comment]
Fixed, evidently.

**Comment by SicariusNoctis** [comment]
Still appears not to work with the following URL: https://mail.google.com/tasks/canvas?pli=1

Test case:

`@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document url-prefix("https://mail.google.com/tasks/canvas") {

  .J {
    background-color: #333 !important;
    /* filter: invert(100%); */
  }
  
  .Z {
    color: #ccc !important;
  }
  
  .o, .k, .p, .i, .Mb {
    border-color: #444 !important;
  }
  
}`

**Comment by Mottie** [comment]
@SicariusNoctis Google changes element class names with every new page load. Target elements using a nodeName and DOM structure (e.g. `body > div > table`).

**Comment by SicariusNoctis** [comment]
I don't think that's the issue here: the class names stay consistent, or at the very least, every time I refresh the page. The problem is, they are inside an iframe, and there appears to be no way to target them.

**Comment by tophf** [comment]
> Still appears not to work with the following URL: https://mail.google.com/tasks/canvas?pli=1

Can't reproduce on Chrome 53.0.2767.4 dev-m.

With the style applied:
![2-fs8](https://cloud.githubusercontent.com/assets/1310400/16226801/caa42d66-37b5-11e6-91d4-65e2f6c1ccdc.png)

Without:
![1-fs8](https://cloud.githubusercontent.com/assets/1310400/16226807/cf5b2850-37b5-11e6-8579-6efcab889224.png)

**Comment by SicariusNoctis** [comment]
This is on Firefox 47.0 (release) running Stylish 2.0.6 (release).

**Comment by tophf** [comment]
There's a separate issue #166 as Firefox's Chrome-compatible WebExtensions API is still incomplete.

**Comment by j-ulrich** [comment]
Still doesn't work for me with a `src="javascript:"""` iframe in Chrome 58 (64-bit, Win7).
Unfortunately, I cannot link to the page because it's not publicly accessible. But it's a Confluence page being edited.
Am I missing something? Do I have to add "about:blank" to the URL matching rules of the design or something like that?

**Comment by tophf** [comment]
@j-ulrich, Stylish seems to be on indefinite hiatus. Try [Stylus](https://github.com/openstyles/stylus) instead.
